apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "squidex.fullname" . }}
  labels:
    {{- include "squidex.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "squidex.selectors" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "squidex.selectors" . | indent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: orleans
              containerPort: 11111
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
          
          {{- $mongoDefaultConnectionString := printf "mongodb://%s" (include "squidex.mongoDefaultHostname" .) }}
          {{- if .Values.env.EVENTSTORE__MONGODB__CONFIGURATION }}
          {{- else }}
            - name: "EVENTSTORE__MONGODB__CONFIGURATION"
              value: {{ $mongoDefaultConnectionString | quote }}
          {{- end }}
          {{- if .Values.env.STORE__MONGODB__CONFIGURATION }}
          {{- else }}
            - name: "STORE__MONGODB__CONFIGURATION"
              value: {{ $mongoDefaultConnectionString | quote }}
          {{- end }}
          {{- if .Values.env.URLS__BASEURL }}
          {{- else }}
            - name: "URLS__BASEURL"
              value: {{ include "squidex.internalDnsName" . | quote }}
          {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
