version: '2.1'
services:
  squidex_mongo:
    image: mongo:latest
    command: mongod --replSet -rs0
    ports:
      - "27017:27017"
    restart: always
    
  squidex_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
    restart: always